src/Entity/Aircraft.php
<?php

namespace App\Entity;

use App\Repository\AircraftRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\ManyToOne;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AircraftRepository", repositoryClass=AircraftRepository::class)
 */
class Aircraft
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(pattern="/^\d{10}$/")
     */
    private $registration_number;

    /**
     * @ManyToOne(targetEntity="AircraftModel")
     * @JoinColumn(name="model_id", referencedColumnName="id")
     */
    private $model;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRegistrationNumber(): ?string
    {
        return $this->registration_number;
    }

    public function setRegistrationNumber(string $registration_number): self
    {
        $this->registration_number = $registration_number;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * @param mixed $model
     * @return Aircraft
     */
    public function setModel($model)
    {
        $this->model = $model;
        return $this;
    }
}

src/Entity/Departure.php
<?php

namespace App\Entity;

use App\Repository\DepartureRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=DepartureRepository::class)
 */
class Departure
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Flight::class, inversedBy="departures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $flight;

    /**
     * @ORM\Column(type="date")
     */
    private $departure_date;

    /**
     * @Assert\IsTrue(message = "Le pilote et le copilote ne peuvent pas être la même personne")
     */
    public function isPilotEqualCopilot()
    {
        return $this->getPilot()->getId() != $this->getCopilot()->getId();
    }
    /**
     * @ORM\ManyToOne(targetEntity=Pilot::class, inversedBy="departures1")
     * @ORM\JoinColumn(nullable=false)
     */
    private $pilot;

    /**
     * @ORM\ManyToOne(targetEntity=Pilot::class, inversedBy="departures2")
     * @ORM\JoinColumn(nullable=false)
     */
    private $copilot;

    /**
     * @Assert\IsTrue(message = "Le chef de cabine et l'assistant de cabine ne peuvent pas être la même personne")
     */
    public function isPurserEqualCrew()
    {
        return $this->getPurser()->getId() != $this->getCrew()->getId();
    }
    /**
     * @ORM\ManyToOne(targetEntity=AirCrew::class, inversedBy="departures1")
     * @ORM\JoinColumn(nullable=false)
     */
    private $purser;

    /**
     * @ORM\ManyToOne(targetEntity=AirCrew::class, inversedBy="departures2")
     * @ORM\JoinColumn(nullable=false)
     */
    private $crew;

    /**
     * @ORM\Column(type="integer")
     */
    private $passengers;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFlight(): ?Flight
    {
        return $this->flight;
    }

    public function setFlight(?Flight $flight): self
    {
        $this->flight = $flight;

        return $this;
    }

    public function getDepartureDate(): ?\DateTimeInterface
    {
        return $this->departure_date;
    }

    public function setDepartureDate(\DateTimeInterface $departure_date): self
    {
        $this->departure_date = $departure_date;

        return $this;
    }

    public function getPilot(): ?Pilot
    {
        return $this->pilot;
    }

    public function setPilot(?Pilot $pilot): self
    {
        $this->pilot = $pilot;

        return $this;
    }

    public function getCopilot(): ?Pilot
    {
        return $this->copilot;
    }

    public function setCopilot(?Pilot $copilot): self
    {
        $this->copilot = $copilot;

        return $this;
    }

    public function getPassengers(): ?int
    {
        return $this->passengers;
    }

    public function setPassengers(int $passengers): self
    {
        $this->passengers = $passengers;

        return $this;
    }

    public function addOnePassenger(): self
    {
        $this->passengers += 1;

        return $this;
    }

    public function getAvailablePlaces(): ?int
    {
        return $this->flight->getAircraft()->getModel()->getCapacity() - $this->passengers;
    }



    /**
     * @return mixed
     */
    public function getPurser()
    {
        return $this->purser;
    }

    /**
     * @param mixed $purser
     * @return Departure
     */
    public function setPurser($purser)
    {
        $this->purser = $purser;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getCrew()
    {
        return $this->crew;
    }

    /**
     * @param mixed $crew
     * @return Departure
     */
    public function setCrew($crew)
    {
        $this->crew = $crew;
        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getArrivalDate(): ?\DateTimeInterface
    {
        $total_time = (int) ($this->flight->getDepartTime()->format('H')) + $this->flight->getDuration();
        $extra_days = (int) ($total_time / 24);
        return $this->departure_date->modify('+'.$extra_days.' days');
    }
}

src/Entity/Flight.php
<?php

namespace App\Entity;

use App\Repository\FlightRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\ORM\Mapping\OneToOne;

/**
 * @ORM\Entity(repositoryClass=FlightRepository::class)
 */
class Flight
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $depart_day;

    /**
     * @ORM\Column(type="integer")
     */
    private $duration;

    /**
     * @ManyToOne(targetEntity="Airport")
     * @JoinColumn(name="depart_airport_id", referencedColumnName="id")
     */
    private $depart_airport;

    /**
     * @ManyToOne(targetEntity="Airport")
     * @JoinColumn(name="arrival_airport_id", referencedColumnName="id")
     */
    private $arrival_airport;

    /**
     * @ManyToOne(targetEntity="Aircraft")
     */
    private $aircraft;

    /**
     * @ORM\OneToMany(targetEntity=Departure::class, mappedBy="flight")
     */
    private $departures;

    /**
     * @ORM\Column(type="time")
     */
    private $depart_time;

    public function __construct()
    {
        $this->departures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDepartDay(): ?string
    {
        return $this->depart_day;
    }

    public function getDepartDayTranslated(): ?string
    {
        switch ($this->depart_day) {
            case "monday":
                return "Lundi";
            case "tuesday":
                return "Mardi";
            case "wednesday":
                return "Mercredi";
            case "thursday":
                return "Jeudi";
            case "friday":
                return "Vendredi";
            case "saturday":
                return "Samedi";
            case "sunday":
                return "Dimanche";
        }
    }

    public function setDepartDay(string $depart_day): self
    {
        $this->depart_day = $depart_day;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getDepartAirport()
    {
        return $this->depart_airport;
    }

    /**
     * @param mixed $depart_airport
     * @return Flight
     */
    public function setDepartAirport($depart_airport)
    {
        $this->depart_airport = $depart_airport;
        return $this;
    }

    /**
     * @param mixed $arrival_airport
     * @return Flight
     */
    public function setArrivalAirport($arrival_airport)
    {
        $this->arrival_airport = $arrival_airport;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getArrivalAirport()
    {
        return $this->arrival_airport;
    }

    /**
     * @return mixed
     */
    public function getAircraft()
    {
        return $this->aircraft;
    }

    /**
     * @param mixed $aircraft
     * @return Flight
     */
    public function setAircraft($aircraft)
    {
        $this->aircraft = $aircraft;
        return $this;
    }

    /**
     * @return Collection|Departure[]
     */
    public function getDepartures(): Collection
    {
        return $this->departures;
    }

    public function addDeparture(Departure $departure): self
    {
        if (!$this->departures->contains($departure)) {
            $this->departures[] = $departure;
            $departure->setFlight($this);
        }

        return $this;
    }

    public function removeDeparture(Departure $departure): self
    {
        if ($this->departures->contains($departure)) {
            $this->departures->removeElement($departure);
            // set the owning side to null (unless already changed)
            if ($departure->getFlight() === $this) {
                $departure->setFlight(null);
            }
        }

        return $this;
    }

    public function getDepartTime(): ?\DateTimeInterface
    {
        return $this->depart_time;
    }

    public function setDepartTime(\DateTimeInterface $depart_time): self
    {
        $this->depart_time = $depart_time;
        return $this;
    }

    public function getArrivalTime(): ?\DateTimeInterface
    {
        $depart_time = $this->depart_time;
        return $depart_time->modify('+'.$this->duration.' hours');
    }

}

src/Controller/BookingController.php
<?php


namespace App\Controller;

use App\Entity\Departure;
use App\Repository\DepartureRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BookingController extends AbstractController
{

    /**
     * @var string
     */
    private $form_path;

    public function __construct() {
        $this->form_path = 'pages/booking/_form.html.twig';
    }

    /**
     * @Route("/booking/index", name="booking.index")
     * @param DepartureRepository $repository
     * @return Response
     */
    public function index(DepartureRepository $repository): Response {
        $departures = $repository->findAllNext();
        return $this->render('pages/booking/index.html.twig', [
            'departures' => $departures
        ]);
    }

    /**
     * @Route("/departure/{id}/booking/create", name="booking.new")
     * @param Request $request
     * @param Departure $departure
     * @return Response
     */
    public function new(Departure $departure, Request $request):Response {
        $user = $this->getUser();

        return $this->render('pages/booking/booking.html.twig', [
            'path' => $this->form_path,
            'departure' => $departure,
            'user' => $user,
        ]);

    }
}

templates/pages/booking/_form.html.twig
{{ form_start(form) }}

<div class="row">
    <div class="col-md-4">{{ form_row(form.surname) }}</div>
    <div class="col-md-4">{{ form_row(form.firstname) }}</div>
</div>

<div class="row">
    <div class="col-md-4">{{ form_row(form.address) }}</div>
</div>


{{ form_widget(form) }}
<button style="float: right; font-size: 1.5rem" class="btn btn-primary">{{ button | default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/pages/booking/booking.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container mt-4 ">
        <h1>Réservation</h1>
        <br />
        <h2>Vos informations</h2>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Passager</h5>
                <div class="card-text">
                    Nom : {{ user.surname }} <br />
                    Prénom : {{ user.firstname }} <br />
                    Adresse : {{ user.address }} <br />
                    E-mail : {{ user.email }} <br />
                </div>
            </div>
        </div>
        <br />
        <div>
            <h2>Vol n° {{ departure.flight.id }}</h2>
            <h4>Appareil : {{ departure.flight.aircraft.registrationNumber }} (Modèle {{ departure.flight.aircraft.model.name }})</h4>
            <br />
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Départ : {{ departure.departureDate.format('d/m/Y') }} à {{ departure.flight.DepartTime.format('H:i') }}</h5>
                    <div class="card-text">
                        Aéroport : {{ departure.flight.departAirport.name }} ({{ departure.flight.departAirport.iata }}) <br />
                        Ville : {{ departure.flight.departAirport.city }} <br />
                        Pays : {{ departure.flight.departAirport.country }}
                    </div>
                </div>
            </div>
            <br />
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Arrivée : {{ departure.getArrivalDate.format('d/m/Y') }} à {{ departure.flight.getArrivalTime.format('H:i') }}</h5>
                    <div class="card-text">
                        Aéroport : {{ departure.flight.arrivalAirport.name }} ({{ departure.flight.arrivalAirport.iata }}) <br />
                        Ville : {{ departure.flight.arrivalAirport.city }} <br />
                        Pays : {{ departure.flight.arrivalAirport.country }}
                    </div>
                </div>
            </div>
        </div>
        <br />
        <a style="float:right;font-size: 1.5rem;" href="{{ path('ticket.new', {
            departure_id: departure.id,
            user_id: user.id
        }) }}"
           class="btn btn-primary">Confirmer la réservation</a>
    </div>
{% endblock %}

templates/pages/booking/index.html.twig
{% extends 'base.html.twig' %}

{% block body  %}
    <div class="jumbotron text-center">
        <h1>Centrale Airline</h1>
    </div>
    <div class="container" style="max-width: 1500px">
        <h2>Les prochains vols</h2>
        <br />
        <div class="row" style="display: flex">
            <div class="column" style="flex: 50%">
                <h3> Vols nationaux</h3>
                {% for departure in departures %}
                    {% if not (departure.flight.departAirport.Country != "France" or departure.flight.arrivalAirport.Country != "France") %}
                        {{ include('departure.html.twig', {departure: departure}) }}
                    {% endif %}
                {% endfor %}
            </div>
            <div class="column" style="flex: 50%">
                <h3> Vols internationaux</h3>
                {% for departure in departures %}
                    {% if departure.flight.departAirport.Country != "France" or departure.flight.arrivalAirport.Country != "France" %}
                        {{ include('departure.html.twig', {departure: departure}) }}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <br />
    </div>

{% endblock %}

templates/pages/booking/ticket.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container mt-4 ">
    <h1> Réservation confirmée </h1>
    <br />
    <div class="card">
        <div class="card-body">
            <h5 class="card-title"> Nous vous remercions {{ user.firstname }} pour votre confiance. Votre réservation a bien été enregistrée.</h5>
            <div class="card-text">
                Vous devez télécharger et <b>conserver soigneusement</b> votre billet jusqu'à l'embarquement :
                <a href="{{ path('ticket.show', {id: ticket.id}) }}" target="_blank">billet à télécharger</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}